---
title: "Assignment 2"
author: "Namrata R"
date: "09/09/2019"
output: html_document
---
```{r}

```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
#packages used
require(plotly)
```
```{r}
#path
path1='C:\\Users\\rames\\Downloads\\dataset\\fitness_data.csv'
```

## R Markdown

```{r}
s<-read.csv(file=path1)
#reading csv and storing into dataframe fitness_data
fitness_data <- data.frame(read.csv(file=path1,header=TRUE, sep=","))
#fitness_data=na.omit(fitness_data)
x<-dim(fitness_data)
#x

#colnames(fitness_data)
```

```{r}

transforms=list(list(type='filter',target=~subID,operation='=',value=unique(fitness_data$subID)))
#transforms

#getting names of all columns and choosing only the attributes that need to be analysed against timestamp
colNames<- names(fitness_data)
#colNames
colNames<-colNames[-which(colNames=='timestamp..in.seconds.')]
colNames<-colNames[-which(colNames=='activityID')]
colNames<-colNames[-which(colNames=='subID')]
#colNames

```


```{r}


df<- fitness_data

## Adding trace directly here with first attribute of heart rate
p <- plot_ly(
  
      fitness_data,
      type = "scatter",
      mode = "lines",
      x = ~timestamp..in.seconds.,
  #add_trace(y = ~heartrate.during.activity..bpm., name = 'trace 0',mode = 'lines') 
 y = ~heartrate.during.activity..bpm., 
  name=colNames[1],
  #creating a filter to choose based on "subID"
    transforms=list(list(type='filter',target=~subID,operation='=',value=unique(fitness_data$subID)[1])),
 height=500
  )
for (col in colNames[-1]) {
#adding the rest of the attributes that need to be analyzed against timestamp
  p <- p %>% add_lines(x = ~c, y = fitness_data[[col]], name = col, visible = FALSE)
}

p <- p %>%
    layout(
      title = "Variation of parameters as subject performs activity over time ",
      #creating a slider for the timestamp range(x axis)
     xaxis = list(title = "timestamp(in seconds)",rangeslider = list(type = "int",thickness=0.2)),
      yaxis = list(title = colNames[1]),
     showlegend = FALSE,
      updatemenus = list(
        #dropdown for each unique subID
       list( type='dropdown',active=0,
             x=1,
             y=1.6,
            buttons=list(
                list(method="restyle",args=list("transforms[0].value",unique(fitness_data$subID)[1]),label=unique(fitness_data$subID)[1]),
                list(method="restyle",args=list("transforms[0].value",unique(fitness_data$subID)[2]),label=unique(fitness_data$subID)[2]),
                list(method="restyle",args=list("transforms[0].value",unique(fitness_data$subID)[3]),label=unique(fitness_data$subID)[3]),
                list(method="restyle",args=list("transforms[0].value",unique(fitness_data$subID)[4]),label=unique(fitness_data$subID)[4]),
                list(method="restyle",args=list("transforms[0].value",unique(fitness_data$subID)[5]),label=unique(fitness_data$subID)[5]),
                list(method="restyle",args=list("transforms[0].value",unique(fitness_data$subID)[6]),label=unique(fitness_data$subID)[6]),
                list(method="restyle",args=list("transforms[0].value",unique(fitness_data$subID)[7]),label=unique(fitness_data$subID)[7]),
                list(method="restyle",args=list("transforms[0].value",unique(fitness_data$subID)[8]),label=unique(fitness_data$subID)[8]),
               list(method="restyle",args=list("transforms[0].value",unique(fitness_data$subID)[9]),label=unique(fitness_data$subID)[9])
              )
              ),
        #dropdown for each column
        list(
            y = 1.9,
            x=1,
            type='dropdown',active=0,
            ## Add all buttons at once using lapply
           buttons = lapply(colNames, function(col) {
             list(method = "update",
             args = list(
               #"y", list(fitness_data[[col]]), 
               list("visible"= colNames == col),list("yaxis" =list(title = col))),  # put it in a list
             label = col)
              
            })
        )
        
      )
    )

print(p)

```

